In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_html("https://github.com/codebasics/py/blob/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")[0]

In [4]:
df.drop(columns=("Unnamed: 0"),inplace=True)

In [5]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [8]:
df.rename(columns={"test_score(out of 10)":"test_score"},inplace=True)

In [9]:
df.rename(columns={"interview_score(out of 10)":"interview"},inplace=True)

In [10]:
df.head()

experience  test_score  interview  salary($)
0        NaN         8.0          9      50000
1        NaN         8.0          6      45000
2       five         6.0          7      60000
3        two        10.0         10      65000
4      seven         9.0          6      70000

In [12]:
df.isna().sum()

experience    2
test_score    1
interview     0
salary($)     0
dtype: int64

In [13]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5583 sha256=947ea987da7e6aacfcb010d99e0456eca9b63c2526a0780f354431cc481663f0
  Stored in directory: c:\users\ayub_\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [15]:
df.experience=df.experience.fillna("zero")
df

experience  test_score  interview  salary($)
0       zero         8.0          9      50000
1       zero         8.0          6      45000
2       five         6.0          7      60000
3        two        10.0         10      65000
4      seven         9.0          6      70000
5      three         7.0         10      62000
6        ten         NaN          7      72000
7     eleven         7.0          8      80000

In [16]:
from word2number import w2n

In [17]:
df.experience=df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview  salary($)
0           0         8.0          9      50000
1           0         8.0          6      45000
2           5         6.0          7      60000
3           2        10.0         10      65000
4           7         9.0          6      70000
5           3         7.0         10      62000
6          10         NaN          7      72000
7          11         7.0          8      80000

In [20]:
import math
med_test=math.floor(df.test_score.mean())
med_test

7

In [21]:
df["test_score"]=df["test_score"].fillna(med_test)
df

experience  test_score  interview  salary($)
0           0         8.0          9      50000
1           0         8.0          6      45000
2           5         6.0          7      60000
3           2        10.0         10      65000
4           7         9.0          6      70000
5           3         7.0         10      62000
6          10         7.0          7      72000
7          11         7.0          8      80000

In [26]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview']],df['salary($)'])

LinearRegression()

In [27]:
reg.predict([[2,9,6]])

C:\Users\ayub_\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [28]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [29]:
reg.intercept_

14992.65144669314

In [30]:
2922.26901502*2+2221.30909959*9+2147.48256637*6+14992.65144669314

53713.86677126314

In [31]:
reg.predict([[12,10,10]])

C:\Users\ayub_\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [32]:
reg.predict([[5,6,6]])

C:\Users\ayub_\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([55816.74651754])